### ISSUE TITLE
Fill the board

### ISSUE THREAD

**Issue by yupichkin** [i1ich/AR-Project-SPbSTU-2021#1]
Fill the board with tasks for the next sprint

**Comment by pv6** [comment]
1. Пометьте пожалуйста задачи в To Do как 1й спринт. Задачу заполнить доску лучше создавать новую на каждый спринт, а не открывать старую. Сейчас уже ладно, но со следующего спринта давайте так.
2. Нужны ещё задачи "Добавить описание проекта", "Добавить сравнение с аналогами", "Добавить список команды" (с пометками, кто тех-лид и тим-лид), "Добавить стиль кодирования" и "Добавить требования к комментарию коммита".
3. Если вы собираетесь использовать эпики в их оригинальном значении: очень крупные задачи, которые решаются несколько спринтов - то сделайте для них отдельную колонку. В In Progress должны висеть уже конкретные атомарные задачи, не больше одной на человека за раз.
4. Совсем сделанные задачи закрывайте, не оставляйте висеть в Done. Закрывать можно например по окончанию спринта, или по сливанию соответствующей ветки, решать вам.

**Comment by pv6** [comment]
5. Нужны ещё задачи "Добавить интеграцию Github в Slack" и "Добавить интеграцию Zenhub в Slack"
Что подразумевают: в слаке сделайте отдельный канал "feed". В него подрубите соответствующих ботов:
Гитхаб: https://arprojectspbstu2021.slack.com/apps/A8GBNUWU8-github 
Зенхаб: https://blog.zenhub.com/add-to-slack/

**Comment by pv6** [comment]
1. Не все задачи помечены как первый спринт. Можно это сделать массово, если нажать на шестеренку сверху колонки To Do и там есть выбрать все. Дальше им можно массово выставлять людей, milestone и т.д.
2. Не хватает ещё задачи "Добавить список команды"
