### ISSUE TITLE
Добавить описание проекта.

### ISSUE THREAD

**Issue by yupichkin** [i1ich/AR-Project-SPbSTU-2021#19]

**Comment by pv6** [comment]
Посмотрите про markdown language и исправьте пожалуйста, чтобы всё было не в одну строчку. Если редактировать напрямую на гитхабе, то там есть кнопка Preview.

![image.png](https://images.zenhubusercontent.com/5c7d470fa3de12186f507ae7/3a6d0fee-b96c-42d2-b5cb-627624a8e1d5)
