### ISSUE TITLE
Добавить требования к комментарию коммита

### ISSUE THREAD

**Issue by yupichkin** [i1ich/AR-Project-SPbSTU-2021#21]

**Comment by pv6** [comment]
Если честно, не понял по вашему описанию, как должен выглядеть комментарий. Нужно добавить пример.
Подписывать имя и дату каждый раз большого смысла нет, гитхаб это всё делает за вас.

Я бы посоветовал сделать похоже на ваших коллег. Формы глаголов и т.д. на ваше усмотрение, но номер задачи в начале советую добавить - это удобная вещь.

![image.png](https://images.zenhubusercontent.com/5c7d470fa3de12186f507ae7/3d19775d-1282-4c73-86e9-870d026af5ca)

**Comment by pv6** [comment]
Добавьте пожалуйста пример коммита.
Для тире есть символ "—", будет лучше смотреться (alt + 0 1 5 1 на нампаде/скопипастить из этого комментария)

**Comment by pv6** [comment]
В описании написано инфинитив, а в примере прошедшее время
