### ISSUE TITLE
Fill the board

### ISSUE THREAD

**Issue by yupichkin** [i1ich/AR-Project-SPbSTU-2021#24]

**Comment by pv6** [comment]
1. Не очень понял задачу с Bottleneck, зачем отдельная на каждого? Если имеется ввиду создать и залить проект, это достаточно сделать один раз одним человеком => 1 задача. И так же единичная задача добавить метку с кубом. Посмотреть видео и т.д. входит скорее в Unity tutorial.
На каждого имеет смысл сделать задачу забилдить апк себе на телефон. Если это имелось ввиду, то надо переименовать эти задачи.
2. Нужны следующие задачи на артефакты:
"Инструкция по установке для разработчиков" (ваша версия юнити, ссылка на скачивание юнити, ...)
"Инструкция по запуску" (скачать апк, поставить апк)
"Целевая платформа" (Андроид)
"Системные требования и ограничения" (минимальная версия андроида, память, требования к железу для AR если есть)
"Release-версия сборки инкремента" (это в конце спринта ваш итоговый апк, какой будет)
"Release notes"
Задачи на артефакты меня ассайните тоже, и я их ревьюю

**Comment by yupichkin** [comment]
Понял ошибку за Bottleneck. Изначально создал индивидуальные задания чтобы каждый мог двигать только своё задание по доске. Но в случае выполнения Bottleneck, остальные задания становятся не актуальными. Теперь же это групповое задание, которое может двигать каждый.
